/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { getReservedBooksByUser } from '../fn/reservation/get-reserved-books-by-user';
import { GetReservedBooksByUser$Params } from '../fn/reservation/get-reserved-books-by-user';
import { PageResponseReservedBookResponse } from '../models/page-response-reserved-book-response';
import { save } from '../fn/reservation/save';
import { Save$Params } from '../fn/reservation/save';

@Injectable({ providedIn: 'root' })
export class ReservationService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `save()` */
  static readonly SavePath = '/reservations/{book-id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `save()` instead.
   *
   * This method doesn't expect any request body.
   */
  save$Response(params: Save$Params, context?: HttpContext): Observable<StrictHttpResponse<number>> {
    return save(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `save$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  save(params: Save$Params, context?: HttpContext): Observable<number> {
    return this.save$Response(params, context).pipe(
      map((r: StrictHttpResponse<number>): number => r.body)
    );
  }

  /** Path part for operation `getReservedBooksByUser()` */
  static readonly GetReservedBooksByUserPath = '/reservations';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getReservedBooksByUser()` instead.
   *
   * This method doesn't expect any request body.
   */
  getReservedBooksByUser$Response(params?: GetReservedBooksByUser$Params, context?: HttpContext): Observable<StrictHttpResponse<PageResponseReservedBookResponse>> {
    return getReservedBooksByUser(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getReservedBooksByUser$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getReservedBooksByUser(params?: GetReservedBooksByUser$Params, context?: HttpContext): Observable<PageResponseReservedBookResponse> {
    return this.getReservedBooksByUser$Response(params, context).pipe(
      map((r: StrictHttpResponse<PageResponseReservedBookResponse>): PageResponseReservedBookResponse => r.body)
    );
  }

}
