/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ReservedBookResponse } from '../models/reserved-book-response';
export interface PageResponseReservedBookResponse {
  content?: Array<ReservedBookResponse>;
  first?: boolean;
  last?: boolean;
  number?: number;
  size?: number;
  totalElements?: number;
  totalPages?: number;
}
